[tool.poetry]
name = "python-works"
version = "0.1.0"
description = "Just code in python"
authors = ["Jairam B <b.jairam0512@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
